# Generated by Django 3.1.4 on 2021-10-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField(max_length=6)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('add', models.TextField(max_length=150)),
            ],
        ),
    ]
