# Generated by Django 3.1.4 on 2021-10-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empno',
            field=models.IntegerField(),
        ),
    ]
